### ISSUE TITLE
The finance scripts are not working as it has by_range methods

### ISSUE THREAD

**Issue by sarbjit-longia** [timescale/templates#2]

**Comment by jonatas** [comment]
Hi @sarbjit-longia , probably the version of Timescale you're using is old. Can you confirm you're using the latest versions?

**Comment by sarbjit-longia** [comment]
That issue is resolved as I did not had timescaledb extension installed. To be fair I did not knew if I needed to install that. But now I am stuck at candlestick_agg. Getting error that its not found. Do I need to do something so that that function is available to be used.

**Comment by jonatas** [comment]
Hi @sarbjit-longia, yes, you also need to have timescaledb-toolkit extension installed.

If you use the docker image `timescaledb-ha`, it will contain both extensions.
